'use strict';
const $=id=>document.getElementById(id);
const api='http://127.0.0.1:18765';
let token=document.querySelector('meta[name=local-runner-key]')?.content||sessionStorage.getItem('lottery-key')||'', revision='', dirty=false;
const fragment=new URLSearchParams(location.hash.slice(1));
if(fragment.has('key')){token=fragment.get('key');history.replaceState(null,'',location.pathname);}
async function request(path,body){const response=await fetch(api+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(8000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
const pretty=s=>(s||'Not recorded').replaceAll('_',' ');
function node(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
function render(data){const p=data.profile,a=p.attendance_preferences;revision=data.revision;$('status').textContent=pretty(data.automation.status);$('schedule').textContent=data.automation.schedule_label;$('schedule-note').textContent=data.automation.status==='PAUSED'?'The schedule is paused. A successful live entry test is still needed.':'See Codex for schedule controls and run progress.';$('confirmed').textContent=data.runs.reduce((sum,r)=>sum+(r.entries||[]).filter(e=>e.status==='confirmed').length,0);const latest=data.runs[0];$('last-date').textContent=latest?.date||'No runs';$('run-status').textContent=pretty(latest?.run_status);$('tickets').value=p.ticket_count;$('price').value=p.max_price_per_ticket_usd;$('start').value=a.weekdays.earliest_start;$('matinees').checked=!!a.weekends?.matinees;$('evenings').checked=!!a.weekends?.evenings;$('next-day').checked=!!a.next_day_allowed;$('trips').checked=!!p.calendar.skip_trips_away;$('conflicts').checked=!!p.calendar.skip_ordinary_conflicts;$('priorities').value=(p.show_preferences.prioritized||[]).join('\n');$('exclusions').value=(p.show_preferences.excluded||[]).join('\n');$('email').textContent='Accounts: '+(p.account_email||p.email);$('calendar').textContent='Calendar: '+p.calendar.account+' · Partiful included · '+p.calendar.access_method;$('accounts').replaceChildren();for(const [name,account]of Object.entries(p.accounts||{})){const row=node('div','');row.className='account';row.append(node('strong',pretty(name)),node('span',pretty(account.status)));$('accounts').append(row);}$('history').replaceChildren();if(!data.runs.length)$('history').append(node('p','No runs recorded yet.'));for(const run of data.runs){const details=document.createElement('details');details.open=run===latest;details.append(node('summary',run.date+' · '+pretty(run.run_status)));if(run.note)details.append(node('p',run.note));const wrap=document.createElement('div');wrap.className='table-wrap';const table=document.createElement('table');const head=node('tr','');for(const h of ['Show / provider','Status','Details'])head.append(node('th',h));table.append(head);for(const e of [...(run.entries||[]),...(run.checks||[])]){const row=node('tr','');for(const value of [e.show||e.provider,pretty(e.status),e.confirmation_evidence||e.evidence||e.note||e.performance_datetime||'—'])row.append(node('td',typeof value==='object'?JSON.stringify(value):value));table.append(row);}wrap.append(table);details.append(wrap);$('history').append(details);}dirty=false;}
async function load(){try{$('message').textContent='';const data=await request('/api/state');render(data);sessionStorage.setItem('lottery-key',token);$('token').value='';$('connection').textContent='Private runner connected';$('connect').hidden=true;$('dashboard').hidden=false;$('refresh').hidden=false;}catch(e){$('message').textContent='Could not connect: '+e.message+'. Check that the runner is running and the key is correct.';$('connection').textContent='Disconnected';$('dashboard').hidden=true;$('connect').hidden=false;}}
$('connect-form').onsubmit=e=>{e.preventDefault();token=$('token').value.trim();load();};
$('refresh').onclick=()=>{if(!dirty||confirm('Discard unsaved preference changes?'))load();};
$('preferences').oninput=()=>{dirty=true;$('save-status').textContent='Unsaved changes';};
$('preferences').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;const lines=id=>$(id).value.split('\n').map(s=>s.trim()).filter(Boolean);try{await request('/api/preferences',{revision,ticket_count:Number($('tickets').value),max_price_per_ticket_usd:Number($('price').value),weekday_start:$('start').value,weekend_matinees:$('matinees').checked,weekend_evenings:$('evenings').checked,next_day_allowed:$('next-day').checked,skip_trips_away:$('trips').checked,skip_ordinary_conflicts:$('conflicts').checked,prioritized:lines('priorities'),excluded:lines('exclusions')});await load();$('save-status').textContent='Saved to your runner. Applies on the next run.';}catch(err){$('save-status').textContent=err.message;}finally{$('save').disabled=false;}};
$('disconnect').onclick=()=>{token='';sessionStorage.removeItem('lottery-key');$('dashboard').hidden=true;$('connect').hidden=false;$('refresh').hidden=true;$('connection').textContent='Disconnected';};
$('copy-request').onclick=async()=>{try{await navigator.clipboard.writeText('Run a live Broadway lottery test using my saved preferences. Keep the schedule paused until verified.');$('message').textContent='Copied. Paste into your Broadway Codex task.';}catch{$('message').textContent='Ask your Broadway Codex task: Run a live lottery test using my saved preferences.';}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
const localKey=document.querySelector('meta[name=local-runner-key]');
if(localKey){$('public-dashboard').hidden=false;$('public-dashboard').href='https://dmitri.im/admin/#key='+encodeURIComponent(token);localKey.remove();}
if(token)load();
